

export class PDV {
    nombre:     string;
    id:         string;
    direccion:  string;
    contacto:   string;
    telefonoContacto: string;
    diasVisita: string;
    horaVisita: string;
    latitud:    number;
    longitud:   number;
    visitado:   boolean;
    orden:      number;

    constructor( id: string, nombre: string, direccion: string, contacto: string, telContacto: string, dias: string, hora: string, latitud: number, longitud: number ){
      this.nombre = nombre;
      this.id = id;
      this.direccion = direccion;
      this.contacto = contacto;
      this.telefonoContacto = telContacto;
      this.diasVisita = dias;
      this.horaVisita = hora;
      this.latitud = latitud;
      this.longitud = longitud;
      this.visitado = false;
      this.orden = 0;
    }
}

// Generated by https://quicktype.io

export interface ClientesBD {
  cod_Zon:                       string;
  cod_Clt:                       string;
  nom_Clt:                       string;
  dir_Clt:                       string;
  nom_Cto:                       string;
  num_Tel:                       string;
  longitud:                      number;
  latitud:                       number;
  altitud:                       number;
  fechA_ACTUALIZACION_UBICACION: Date;
}



