
export class Productos {
    id: string;
    idCliente: string;
    idIslena: string;
    nombre: string;
    precio: number;
    codigoBarras: string;
    barrasCliente: string;
    stock: number;          // 0 = normal; 1 = bajo Stock; -1 = faltante
    seleccionado: boolean;
    imagen: string;

    constructor ( id: string, idCliente: string, idIslena: string, nombre: string, precio: number, codBar: string, barCliente: string, stock: number ){
        this.id = id;
        this.idCliente = idCliente;
        this.idIslena = idIslena;
        this.nombre = nombre;
        this.precio = precio;
        this.codigoBarras = codBar;
        this.barrasCliente = barCliente;
        this.stock = stock;
        this.seleccionado = false;
        this.imagen = "../../../assets/icon/ok.png";
    }
}

// Generated by https://quicktype.io

export interface ProductosBD {
    id:            number;
    idCliente:     string;
    nombre:        string;
    precio:        number;
    codigoBarras:  string;
    barrasCliente: string;
    stockMinimo:   number;
    idProduc:      string;
}

// Generated by https://quicktype.io

export interface Articulos {
    articulo:           string;
    descripcion:        string;
    codigO_BARRAS_VENT: string;
}

