
export interface Ruta {
    ruta: string;
    handHeld: string;
    bodega: string;
    agente: string;
    pedido: string;
    devolucion: string;
}

// Generated by https://quicktype.io

export interface RolVisita {
    ruta:    string;
    cliente: string;
    dia:     string;
    orden:   number;
}

