
export interface Ruta {
    ruta: string;
    handHeld: string;
    bodega: string;
    agente: string;
    pedido: string;
    devolucion: string;
    horaSincroniza: Date;
    horaAlmuerzo:   Date;
    latitud1:       number;
    longitud1:      number;
    idMercarista:   string;
    latitud2:       number;
    longitud2:      number;
    almuerzoTime:   boolean;
}

// Generated by https://quicktype.io

export interface RolVisita {
    ruta:    string;
    cliente: string;
    dia:     string;
    orden:   number;
}

export interface Visita {   // Contiene la información del día de la ruta y se actualiza en la tabla Visita_Diaria
    ID:             string;
    ruta:           string;
    horaSincroniza: Date;
    horaAlmuerzo:   Date;
    latitud1:       number;
    longitud1:      number;
    idMercarista:   string;
    latitud2:       number;
    longitud2:      number;
}

