

export interface Ruta {
    ruta: string;
    handHeld: string;
    bodega: string;
    agente: string;
    pedido: string;
    devolucion: string;
}

// Generated by https://quicktype.io

export class RolVisita {
    constructor(
    public ruta:    string,
    public cliente: string,
    public dia:     string,
    public orden:   number,
    ){}
}

export class RutasUbicadas {
    constructor(
        public ruta:    string,
        public orden:   number,
        public latitud: number,
        public longitud: number,
        public cliente: string,
        ){}
}

// Generated by https://quicktype.io

export interface Visita {     // Info de la Tabla Visita Diaria
    id:             string;
    ruta:           string;
    horaSincroniza: Date;
    horaAlmuerzo:   Date;
    latitud1:       number;
    longitud1:      number;
    idMercaderista: string;
    latitud2:       number;
    longitud2:      number;
}

export interface Usuarios {
  empleado: string;
  usuario: string;
  clave: string;
  email: string;
  nombre: string;
}

